pipeline {
    agent any

    stages {
        stage('GitCheckout') {
            steps {
                git credentialsId: '417b718e-af59-4bcd-9c2a-2be8de40a322', url: 'https://github.com/sivak243/JenkinsWebhook'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    def dockerImage = docker.build("my-docker-image:latest", ".")

                    // Additional steps like tagging and pushing the image could go here.
                }
            }
        }
        stage('Docker Run') {
            steps {
                script {
                    def containerId = docker.image("my-docker-image:latest").run('-it')
                    echo "Docker container started with ID: ${containerId}"
                }
            }
        }
    }
}
